### ISSUE TITLE
"Player" has a bug

### ISSUE THREAD

**Issue by AbrasiveBoar902** [gnembon/fabric-carpet#973] opened 2021-07-01 11:51 UTC
It will crash if I use player command to update the update suppression(like put a block nearby)

**Comment by James103** [comment] 2021-07-01 13:46
Likely a duplicate of #942 
Quoting from @gnembon (original comment at https://github.com/gnembon/fabric-carpet/issues/942#issuecomment-866115658):
> Please try with this jar:
> https://github.com/gnembon/fabric-carpet/actions/runs/961294266
> 
> It should resolve this issue.

**Comment by gnembon** [comment] 2021-07-02 13:35
Please try with 1.4.42

**Closed by gnembon** 2021-07-02 13:35 UTC
