### ISSUE TITLE
Possible 4 Way Conflict - Server Freezes on startup

### ISSUE THREAD

**Issue by Blobanium** [gnembon/fabric-carpet#632] opened 2020-12-17 01:19 UTC
So the server Becomes frozen when i attempt to start up the server, the console kicks out errors and freezes the server, i was removing mods to see where the conflict was, i attempted to search the logs to find the issue, after some inspecting i found the Primary conflict to be Carpet, The Others possibly involved were WorldEdit, Bukkit4Fabric, and TicTacs.

Im using Carpet Version 1.4.12

i think Its mainly conflicting with Worldedit because when thats when the server freezing started to happen

For Bukkit4Fabric (A Mod used to enable Bukkit/Spigot/Paper Plugins on fabric), I only had EssentialsX and Clearlagg, However Removing the plugins didn't seem to have any variation at all

and i also found that there is different behavior when using a certain mod combination (I found the possible behaviors to be Infinite Console Spam, Crashing, Or server freezing, or probably just starts up normally without any notable errors and is playable) 

Mods: 
![Capture](https://user-images.githubusercontent.com/45613796/102424708-95893500-3fc0-11eb-8bad-a3ab23802681.PNG)

And the log:
[latest.log](https://github.com/gnembon/fabric-carpet/files/5706369/latest.log)

tell me if there's anything else i need

**Comment by altrisi** [comment] 2020-12-17 03:36
This is caused by recent changes in WorldEdit.

Tracked in WorldEdit at EngineHub/WorldEdit#1605.

Kind-of duplicate of #625.

**Comment by Ghoulboy78** [comment] 2021-02-14 16:51
@Blobanium can be closed now

**Closed** 2021-02-14 22:20 UTC
