### ISSUE TITLE
Scarpet 0/0 equality

### ISSUE THREAD

**Issue by rv3r** [gnembon/fabric-carpet#1776] opened 2023-07-27 22:27 UTC
```
0/0 -> NaN
0/0 == 1 -> true
0/0 == -1 -> true
0/0 == 2 -> true
...
3/0 -> INFINITY
0/0 == 3/0 -> true
```
Bug or WAI?

**Comment by silnarm** [comment] 2023-07-28 04:15
NaN equality has an issue (#1576), and PR to fix (#1577).

The Infinity one is actually the same, 0/0 => NaN == anything.

**Comment by altrisi** [comment] 2023-07-28 12:42
Yes, this is a duplicate of #1576.

**Closed by altrisi** 2023-07-28 12:42 UTC

**Comment by ch-yx** [comment] 2023-07-31 17:57
walk around:
you can create an function `is_nan(x)` by yourself.
if type(x) is number and str(x) is NaN
