### ISSUE TITLE
Optifine 1.16.1 pre 6, 7, 8, 9.

### ISSUE THREAD

**Issue by Slideuwu** [gnembon/fabric-carpet#394] opened 2020-07-24 17:41 UTC
The carpet and carpet extra dont open minecraft with optifine Optifine 1.16.1 pre 6, 7, 8, 9.

**Comment by altrisi** [comment] 2020-07-25 18:49
Are you using the latest Carpet version, 1.4.4? (not sure if compatible with .16.1). Or what version?
In previous versions (<=1.4.3 I think) there was a conflict with Optifine that has been resolved since.
Also, Optifabric is no longer mantained. In [that mod's page](https://github.com/modmuss50/OptiFabric#readme) it explains why and there you can find some (better) alternatives to it.

If you still need/want some specific Optifine feature not available there and would like to use carpet in your world(s), another option you can always use is having carpet in a (local) server and not in the client. You usually don't lose anything, since Carpet is (mostly) server-side (now it has a few client-side features, like actually freezing the render or scarpet shapes, but it's still mostly server-side).
Of course another option is to just use a previous version of OptiFine if those worked correctly for you.

And please provide logs and crash reports for issues (like you kind-of did in sp614x/optifine#4413), else it's difficult to help resolving them.

_Same in Spanish: https://pastebin.com/p32GWrd3 (based in your email signature in that last issue)_

_____
Possible duplicate of #386

**Comment by altrisi** [comment] 2020-07-25 19:00
Ok, 1.4.4 doesn't seem to work in .16.1.
I've made a 1.4.0 version with the OptiFine fix in a fork (check code at https://github.com/altrisi/fabric-carpet/tree/1.16, made by reversing to 1.16.1 commit and then cherry-picking the OF fix).
I haven't tested it with OptiFine (since I don't use it) or extensively, but without it it at least launches and opens a world, and `/carpet` works.
You can try it to see if it works for you by building the JAR from there or by downloading the pre-compiled jar below (you need to unzip it since GitHub doesn't allow JARs in issues):
[fabric-carpet-1.16.1-1.4.0+OFfix.zip](https://github.com/gnembon/fabric-carpet/files/4976196/fabric-carpet-1.16.1-1.4.0%2BOFfix.zip)

**Comment by gnembon** [comment] 2020-07-27 20:48
Check the downloads - I created a ....build2 of 1.4.0 with the OF fix - its a default download for 1.4.0 now. Or pick altrisi's build. 

1.4.0-...build2 is good for 1.16 and 1.16.1

**Comment by gnembon** [comment] 2020-07-27 20:48
will close if that's the problem, or else....

**Comment by MsWolphie** [comment] 2020-08-19 09:42
Hi,

So, with the "build2" for 1.16.1 and the latest release for 1.16.2 both have the same issue with this fix: the game indeed does work now and both mods are working, but now there seems to be an issue with the particles, they look frameraty, even if the game itself runs at a more than decent framerate. Like the particle rate is slower than the framerate itself.

It does work normally with Carpet on its own, and same for Optifine.

(For 1.16.2 I'm using the [Optifabric fork made by Andrews54757](https://github.com/Andrews54757/OptiFabric-updated))

**Comment by gnembon** [comment] 2020-09-04 01:56
its been fixed in 1.16.2 already in 1.4.something

**Closed by gnembon** 2020-09-04 01:56 UTC

**Comment by MsWolphie** [comment] 2020-09-04 22:14
That was more likely a duplicate of https://github.com/gnembon/fabric-carpet/issues/393 I think but my bad
