### ISSUE TITLE
Player named "a" is not spawneable

### ISSUE THREAD

**Issue by Lokemol** [gnembon/fabric-carpet#1212] opened 2021-12-11 19:12 UTC
So, if i try spawning a player named "a" the game says An unexpected error trying to execute that command ( as shown in this image) must say, that players like "1" "c" "b" are spawneable, even accounts named "sldgfsdkb2490320nsvf" with random names are, i think i spawned "a" once in my world, and i don't know what happened, it was A LONG TIME AGO, like at least 8 months, so, maybe it has something to do with that ( i am not sure if i spawned him once, this is a supposition)
https://imgur.com/a/67R9kjg

**Comment by James103** [comment] 2021-12-11 19:23
Can you please run the following commands in that order?
```mcfunction
kill a
carpet superSecretSetting true
player a spawn
```

**Comment by altrisi** [comment] 2023-04-02 12:57
Cannot reproduce in current versions.

**Comment by altrisi** [comment] 2023-04-05 10:09
Going to close this as resolved, though open a new one or ask for reopening if it becomes one again.

**Closed by altrisi** 2023-04-05 10:09 UTC
Labels: bug
