### ISSUE TITLE
un-relogin shadow

### ISSUE THREAD

**Issue by AbrasiveBoar902** [gnembon/fabric-carpet#1320] opened 2022-02-09 03:18 UTC
When I use shadow, I will logout from the server and then the fake player login. This will cause many problems, like item-shadowing lost, and some monsters will lose angry state. Is it possible to make /shadow directly take over the player?

**Comment by CommandLeo** [comment] 2022-02-09 14:23
Duplicate of #1219

**Closed** 2022-04-04 09:09 UTC
