### ISSUE TITLE
Incompatible with Iris

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [gnembon/fabric-carpet#1082] opened 2021-08-30 12:25 UTC
Incompatible with the latest commit of Iris (https://github.com/IrisShaders/Iris/commit/8c03291f78d1d7a312bfb06ed2e48fdab75a7f74 at the time of writing). Crash report: https://gist.github.com/DragonEggBedrockBreaking/320785bdc540a4fd7d39f34052a76aae

**Comment by DragonEggBedrockBreaking** [comment] 2021-08-30 12:26
Issue report on Iris' issue tracker: https://github.com/IrisShaders/Iris/issues/809

**Comment by altrisi** [comment] 2021-08-30 21:08
Isn't this caused by the batched entity rendering iteration that is being removed in the next (Iris) version?

It seems like Carpet's method is already changed (redirected) by the implementation in those dev builds that sorts the entity list, that was committed as "temporarily" (in commit: https://github.com/IrisShaders/Iris/commit/d0a56eea06783c60fb91d66744758bacab49bce7, conflict located at: https://github.com/IrisShaders/Iris/blob/8c03291f78d1d7a312bfb06ed2e48fdab75a7f74/src/main/java/net/coderbot/iris/mixin/MixinWorldRenderer.java#L289-L292).

**Comment by coderbot16** [comment] 2021-09-03 07:19
This was fixed in https://github.com/IrisShaders/Iris/commit/df9a93293c3c0132da50d0aba82d1c07c4e07e9d

**Closed** 2021-09-03 08:52 UTC
