### ISSUE TITLE
Conflict with worldedit

### ISSUE THREAD

**Issue by Jroid8** [gnembon/fabric-carpet#715] opened 2021-02-15 19:12 UTC
When I try to load a world in fabric with worldedit and carpet installed the world loading gets stuck at 0%.
At first, I thought it was worldedit's problem until I tried loading fabric without any mods except fabric API and modmenu, and it worked until I put carpet and try again
I have other mods and I don't know they have a part in this conflict or not

**Comment by altrisi** [comment] 2021-02-15 19:27
Yep, WorldEdit changes in 7.2.1 conflict with Carpet. It affects WorldEdit 7.2.1-7.2.2, and is already fixed in 7.2.3 development versions. It is a known issue. Meanwhile you can use WE 7.2.0 with Carpet. Therefore, this is a duplicate of, let me get that list back...

Duplicate of #698, #688, #645, #632, #625 and EngineHub/WorldEdit#1605

**Closed** 2021-02-16 02:09 UTC
