### ISSUE TITLE
/player attack issue

### ISSUE THREAD

**Issue by SweaterOMG** [gnembon/fabric-carpet#1174] opened 2021-11-18 15:58 UTC
i used /player SweaterOMG (my name) interval 11 and now i cannot get myself to stop attacking in game no matter if i close out the whole launcher or not
tried using /player SweaterOMG stop does not work either

**Comment by gnembon** [comment] 2021-11-27 18:50
I don't think that would be possible.

**Comment by altrisi** [comment] 2022-04-04 09:55
Closing this as there's been no feedback in a while. If it's still an issue, feel free to comment and it can be reopened, or make a new issue.

**Closed by altrisi** 2022-04-04 09:55 UTC

**Comment by rueedolf** [comment] 2023-03-06 15:40
> i used /player SweaterOMG (my name) interval 11 and now i cannot get myself to stop attacking in game no matter if i close out the whole launcher or not tried using /player SweaterOMG stop does not work either

I have the same problem on a 1.19.3 server and it also does this in my singleplayer worlds.
Have you fixed the issue?
Pls let me know

**Comment by altrisi** [comment] 2023-03-08 12:45
Do you have a way to reproduce it with just Carpet? Or could you find a minimal installation.

Please give the exact steps, it'd be very helpful.

I haven't been able to reproduce this, and it's very strange because Carpet doesn't save actions afaik, so they're always reset when reloading.
