### ISSUE TITLE
[@: Can only manipulate existing players] keeps forming

### ISSUE THREAD

**Issue by Anson-MC** [gnembon/fabric-carpet#1813] opened 2023-09-19 00:40 UTC
[@: Can only manipulate existing players]
I have added a player, and then I kill it, and then It log out and the console is like this
[@: Can only manipulate existing players]
[@: Can only manipulate existing players]
[@: Can only manipulate existing players]
[@: Can only manipulate existing players]

**Comment by James103** [comment] 2023-09-19 00:44
Duplicate of https://github.com/gnembon/fabric-carpet/issues/1814 (or vice versa)

**Closed** 2023-09-19 15:38 UTC
