### ISSUE TITLE
auto_lighter.sc not working on surface

### ISSUE THREAD

**Issue by asundrus** [gnembon/fabric-carpet#1448] opened 2022-05-19 09:08 UTC
According to https://github.com/gnembon/fabric-carpet/wiki/How-to-spawn-proof-with-auto_light.sc

The following line needs to be changed
`&& air(lpos) && light(lpos) < 8 && sky_light(lpos) < 8`

But that line does not exist, however, in line 14 in the recent script, this line should control it:
`global_light_ground = true; //Whether or not we want to light the surface`
But no matter what, I can't get this to work.

**Comment by altrisi** [comment] 2022-05-19 10:13
This seems to be an issue with the new version of the script, reported in gnembon/scarpet#317.

As a workaround, you can get the older version and apply the instructions on the wiki page.

Here's a link to the older version: https://github.com/gnembon/scarpet/raw/fe150339ab32283acac0b63e43fcfd63d8f31467/programs/survival/auto_lighter.sc

**Comment by asundrus** [comment] 2022-05-19 11:00
> This seems to be an issue with the new version of the script, reported in [gnembon/scarpet#317](https://github.com/gnembon/scarpet/issues/317).
> 
> As a workaround, you can get the older version and apply the instructions on the wiki page.
> 
> Here's a link to the older version: https://github.com/gnembon/scarpet/raw/fe150339ab32283acac0b63e43fcfd63d8f31467/programs/survival/auto_lighter.sc

Thanks for the reply, it worked.

**Comment by altrisi** [comment] 2022-05-19 17:30
Closing this as a dupe of the issue on the scarpet repo.

**Closed by altrisi** 2022-05-19 17:30 UTC
