### ISSUE TITLE
Using structure box bounding boxes as replacement for box shapes

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#899] opened 2021-06-01 17:49 UTC
(mostly for me, if I get bored enough at some point)

It has been brought to my attention a few+ days ago in the Fabric discord about someone rendering the structure block bounding boxes to vanilla clients as shapes. That could be a better replacement for box displayes in vanilla clients, except that not sure if you can color them.

I'll try to investigate how hard it would be to implement that somehow, at some point, unless you don't think it would be a better replacement if possible.

**Comment by gnembon** [comment] 2021-06-11 03:43
duplicate of #898

**Closed by gnembon** 2021-06-11 03:43 UTC

**Comment by altrisi** [comment] 2021-06-11 05:14
Wow, didn't notice I double submitted. I'm losing skills...
