### ISSUE TITLE
A conflict occurred with the WorldEdit during loading the world

### ISSUE THREAD

**Issue by acaciachan** [gnembon/fabric-carpet#645] opened 2020-12-28 05:43 UTC
[latest.log](https://github.com/gnembon/fabric-carpet/files/5746000/latest.log)
(I also submitted the error report to WordEdit on GitHub)

**Comment by James103** [comment] 2020-12-28 05:52
Duplicate of #625

**Comment by interestingLSY** [comment] 2021-01-07 01:58
Do not use worldedit 7.2.1, use 7.2.0 instead.

**Comment by Ghoulboy78** [comment] 2021-01-28 20:49
@acaciachan fixed

**Comment by DragonEggBedrockBreaking** [comment] 2021-02-02 15:42
So should this be closed now? Due to both being a duplicate *and* fixed in development releases of WE?

**Comment by naturecodevoid** [comment] 2021-02-24 01:20
Is it fixed in 7.2.3?

**Comment by DragonEggBedrockBreaking** [comment] 2021-02-24 11:00
> Edit: Just tested and it is fixed! 🎉

Then I guess this issue should be closed?

**Comment by gnembon** [comment] 2021-02-28 03:32
closing

**Closed by gnembon** 2021-02-28 03:32 UTC
