### ISSUE TITLE
https://prnt.sc/zm7p6e

### ISSUE THREAD

**Issue by VictorGamerLOL** [gnembon/fabric-carpet#714] opened 2021-02-15 15:20 UTC
So I had a random crash and I thought it was due to jumploader 
Jumploader creator told me it was due to a "mixin injection failure with carpet"
Long log: https://paste.ee/p/WKkxK
Short log: https://paste.ee/p/ZfbPn

**Comment by VictorGamerLOL** [comment] 2021-02-15 15:21
Someone also told me to use regular java instead of openjdk but I am not sure really how to do that

**Comment by altrisi** [comment] 2021-02-15 17:59
This is a known incompatibility with WorldEdit 7.2.1-7.2.2. It is already fixed in the development builds of WE 7.2.3, but meanwhile you can use 7.2.0 instead. Duplicate of #698, #688, #645, #632, #625 and EngineHub/WorldEdit#1605

Actually, this is not only the WorldEdit incompatibility, but also the Carpet TIS Addition one (it is the one actually causing the conflict here, WE failure would have come later). To fix it I recommend you downgrade Carpet to 1.4.24, since a recent change in 1.4.25 is causing some problems not only with Carpet TIS Addition but also in some specific situations with Vanilla servers, which will be addressed shortly. Therefore this is also a duplicate of #700.

Wow so many relations.

**Comment by gnembon** [comment] 2021-02-28 03:33
fixed in WE 7.2.3, closing

**Closed by gnembon** 2021-02-28 03:33 UTC
