### ISSUE TITLE
Optimized Tnt isn't exploding blocks on commit "16"

### ISSUE THREAD

**Issue by QPCrummer** [gnembon/fabric-carpet#1181] opened 2021-11-23 00:30 UTC
When enabling it and exploding Tnt, no blocks get broken.

**Comment by gnembon** [comment] 2021-11-23 19:37
what is commit 16?

**Comment by altrisi** [comment] 2021-11-23 20:14
I'd assume "16" means e8f1d85824dabee140af14e7c3a9fb0b8ad9c962, since that's the first commit I could find with that name.

Could you check if this is caused by #1156? (merged as commit 5005268df4ebc2a99b73e78f4c05c68518c675d7)

**Comment by gnembon** [comment] 2021-11-23 21:27
ok, tnt won't blow up blocks now. will take a look

**Comment by gnembon** [comment] 2021-11-23 21:32
@lntricate1 ....

**Closed** 2021-11-23 21:46 UTC
