### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by Noxally** [gnembon/fabric-carpet#439] opened 2020-08-29 15:55 UTC
Scripts such as ai_tracker and overlay do not cause any rendering on fabulous graphics

**Comment by Ghoulboy78** [comment] 2020-08-30 09:35
duplicate of #420

**Comment by gnembon** [comment] 2020-09-04 01:55
https://github.com/gnembon/fabric-carpet/commit/68f545df4f633454a49d8ccfae78ab2fc728ef9e

**Closed by gnembon** 2020-09-04 01:55 UTC
