### ISSUE TITLE
[Mod conflict] Library of Exile+Carpet+WorldEdit=crash

### ISSUE THREAD

**Issue by RDKRACZ** [gnembon/fabric-carpet#625] opened 2020-12-11 11:04 UTC
Weird, I can run Carpet and WorldEdit mod without crash but when I add Library of Exile to mods then mc crashes.
Running Library of Exile with WorldEdit without Carpet doesn't crash.

crash report - https://hatebin.com/balwmiqfud

**Comment by RDKRACZ** [comment] 2020-12-11 11:07
https://github.com/RobertSkalko/Library-of-Exile/issues/1

**Comment by altrisi** [comment] 2020-12-12 15:29
Seems like the causer _may_ be [CardinalComponent's Chunk API](https://github.com/OnyxStudios/Cardinal-Components-API), not "Library of Exile" itself (may be a better place to report, but check if that's the case first), but I'm not sure. It seems to prevent Carpet from finding the method it's trying to mix into.

**Comment by gnembon** [comment] 2020-12-13 05:46
well, just recently WE added some initial support for non-updatable setblocks, mixing into the same place with redirect - that will not end well.

**Comment by altrisi** [comment] 2020-12-17 03:37
True, it has actually been confirmed there.

Well, then this relates to EngineHub/WorldEdit#1605, which is "scheduled" to be fixed in WE 7.2.2.

**Comment by Ghoulboy78** [comment] 2020-12-29 07:51
this is another reason why we r making WorldEdit for scarpet. It's WIP, but idrc, it works.

**Comment by Ghoulboy78** [comment] 2021-01-28 20:42
ok, this is fixed on WE's side, we can close her too now.

**Comment by Ghoulboy78** [comment] 2021-02-14 15:58
k, you can close now @RDKRACZ

**Closed** 2021-02-28 03:33 UTC
Labels: mod compat
