### ISSUE TITLE
player X spawn not working.

### ISSUE THREAD

**Issue by MotazDegmis** [gnembon/fabric-carpet#1876] opened 2024-03-03 10:33 UTC
player X spawn not working.
When the command is executed, nothing happens.
i play Minecraft v1.20.4

**Comment by James103** [comment] 2024-03-03 15:33
What do you get in the client and server logs when running the command?

**Comment by senseiwells** [comment] 2024-03-03 17:02
This is likely to be caused by #1849, which has been fixed.

**Comment by altrisi** [comment] 2024-04-28 20:30
Going to close it then given no information and likely being fixed.

**Closed by altrisi** 2024-04-28 20:30 UTC
