### ISSUE TITLE
Game Crashed 1.21

### ISSUE THREAD

**Issue by 00vvlc** [gnembon/fabric-carpet#1991] opened 2024-09-01 18:14 UTC
The game crashes with carpet and extra carpet, I have no idea why. I leave you the log

https://mclo.gs/Om5CE5G

**Comment by 0xnim** [comment] 2024-09-01 23:36
Duplicate of #1988

Please close Issue

**Closed** 2024-09-01 23:38 UTC

**Comment by 0xnim** [comment] 2024-09-02 00:09
Did you get the fixed pr?

**Comment by 0xnim** [comment] 2024-09-02 00:09
Anyone stubling on this. 

https://github.com/gnembon/fabric-carpet/pull/1937
The build to this pr is available

**Comment by 00vvlc** [comment] 2024-09-02 00:12
> Did you get the fixed pr?
> 

Yes, modifying indium, that mod brings conflict
