### ISSUE TITLE
Server version 1.19 fails to start due to failure to set compatibility level JAVA_17 (client works fine)

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#1464] opened 2022-06-13 18:34 UTC
Whenever I try to start up a Minecraft server, version 1.19 with Fabric and Carpet Mod installed, the server crashes on init with the following: `java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))`

I've tried different combinations of the mods Carpet Mod, Lithium, and Starlight. The only combination that worked was if the server was started with just Lithium mod and only then because it set the compatibility level JAVA_16 which worked.

I've tried different java versions, including:
* Java 17.0.3 from Adoptium
* Java 17.0.3.1 from Oracle
* Java 18.0.1.1 from Oracle

None of them worked and all of them gave the same error.

The client is able to start version 1.19 with all of the mods Carpet Mod, Lithium, and Starlight and is able to successfully set compatibility level JAVA_17. It's just the server that's failing to start.

If this turns out to not be caused by Carpet mod, it will be reposted to one or more of the bug trackers of the other mods being used.

The complete mod list I've tried was:
```
        - carpet 1.4.79
        - fabricloader 0.14.7
        - java 17
        - lithium 0.8.0
        - minecraft 1.19
        - starlight 1.1.0
```

<details>

<summary> The complete error (click to expand) </summary>

```
Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71)
Caused by: java.lang.RuntimeException: Error creating Mixin config carpet.mixins.json for mod carpet
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config carpet.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 4 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 7 more
```

</details>

**Comment by G4lds** [comment] 2022-06-23 23:02
same, i cant make is work

**Comment by altrisi** [comment] 2022-06-27 12:57
That's weird, compatibility level `JAVA_17` is the standard in 1.18+, and your Loader and Java is recent enough to support it too.
Even more weird is I can't reproduce it, so I can't even try to debug why it's happening.

Make sure you've got the correct jar for your Minecraft version and that you're not using a sources/dev jar or something, else I don't really know what could be the issue.

**Comment by altrisi** [comment] 2022-10-02 12:28
Closing assuming this was fixed, if it isn't feel free to comment and I'll reopen it though.

**Closed by altrisi** 2022-10-02 12:28 UTC

**Comment by Hoppingmad9** [comment] 2022-10-22 14:36
For me replacing the server.jar with the above worked
