### ISSUE TITLE
Incompatibility with fabrication

### ISSUE THREAD

**Issue by drakosoldier298** [gnembon/fabric-carpet#688] opened 2021-01-26 15:40 UTC
https://gist.github.com/drakosoldier298/00b71976e5a2df03664f7b37e930adcc
This is a log from a server on apex so custom.jar is fabric

**Comment by altrisi** [comment] 2021-01-26 19:16
I'd say this seems more like the current WorldEdit conflict (therefore, this would be a duplicate of #625, and all its duplicates).

As a workaround before this is fixed, you should use WorldEdit 7.2.0 (or lower) instead with Carpet.

**Comment by Ghoulboy78** [comment] 2021-01-28 20:43
well it0s fixed now @drakosoldier298, update to newest version of WE

**Comment by altrisi** [comment] 2021-01-28 20:49
Note that the WE version which fixed this hasn't been released yet.

**Comment by gnembon** [comment] 2021-02-28 03:34
fixed in 7.2.3, so closing.

**Closed by gnembon** 2021-02-28 03:34 UTC
