### ISSUE TITLE
Game crash during profile entities

### ISSUE THREAD

**Issue by PRRB** [gnembon/fabric-carpet#1607] opened 2022-12-18 22:50 UTC
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2022-12-18 22:45:53
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: Index 17 out of bounds for length 17
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.accept(SortedOps.java:369)
	at it.unimi.dsi.fastutil.objects.Object2LongOpenHashMap$EntrySpliterator.acceptOnIndex(Object2LongOpenHashMap.java:1009)
	at it.unimi.dsi.fastutil.objects.Object2LongOpenHashMap$EntrySpliterator.acceptOnIndex(Object2LongOpenHashMap.java:991)
	at it.unimi.dsi.fastutil.objects.Object2LongOpenHashMap$MapSpliterator.tryAdvance(Object2LongOpenHashMap.java:917)
	at it.unimi.dsi.fastutil.objects.Object2LongOpenHashMap$EntrySpliterator.tryAdvance(Object2LongOpenHashMap.java:991)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at carpet.utils.CarpetProfiler.finalize_tick_report_for_entities(CarpetProfiler.java:321)
	at carpet.utils.CarpetProfiler.finalize_tick_report(CarpetProfiler.java:178)
	at carpet.utils.CarpetProfiler.end_tick_profiling(CarpetProfiler.java:169)
	at net.minecraft.server.MinecraftServer.handler$zce000$stopAsync(MinecraftServer.java:3997)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.handler$zce000$modifiedRunLoop(MinecraftServer.java:3894)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1014431216 bytes (967 MiB) / 3114270720 bytes (2970 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1631
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 27339.33
	Virtual memory used (MB): 12957.97
	Swap memory total (MB): 11264.00
	Swap memory used (MB): 373.88
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		ambientsounds: Ambient Sounds (Fabric) 5.2.13
		appleskin: AppleSkin 2.4.1+mc1.19
		autofish: Autofish 0.9.5-SNAPSHOT
		betterf3: BetterF3 4.0.0
		carpet: Carpet Mod 1.4.84
		carpetskyadditions: Carpet Sky Additions 1.19.2-4.1.3
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		controlling: Controlling For Fabric 10.0+7
		creativecore: CreativeCore (Fabric) 2.9.3
		dark-loading-screen: Dark Loading Screen 1.6.12
		deathlog: DeathLog 0.2.11+1.19
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		fabric-api: Fabric API 0.68.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.22+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.3+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.3+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.2+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.35+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.9+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.12+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.20+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.2+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.0+e7aeff4590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.17+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.22+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.1+0d0f210290
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.29+0d0f210290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabricloader: Fabric Loader 0.14.11
		fastload: Fast Load 2.4.4
		freecam: Freecam 1.1.6
		iknowwhatimdoing: I Know What I'm Doing 4.1.0
		improved-signs: Improved Signs 1.2.0
			omega-config: OmegaConfig 1.2.3-1.18.1
		inventorysorter: Inventory Sorter 1.8.10-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lithium: Lithium 0.10.4
		logical_zoom: Logical Zoom 0.0.17
		malilib: MaLiLib 0.13.0
		minecraft: Minecraft 1.19.2
		minihud: MiniHUD 0.23.3
		modmenu: Mod Menu 4.1.2
		phosphor: Phosphor 0.8.1
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		tooltipfix: ToolTip Fix 1.1.1-1.19
		tooltiptweaks: Tooltip Tweaks 1.1.0
		torohealth: ToroHealth Damage Indicators 1.19-fabric-1
	Server Running: true
	Player Count: 1 / 8; [class_3222['Dread_Nip'/15, l='ServerLevel[∞SkyBye∞]', x=-227.79, y=-61.00, z=140.70]]
	Data Packs: vanilla, Fabric Mods, carpetskyadditions/skyblock
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.11-1.19.2
```

**Comment by altrisi** [comment] 2022-12-26 14:20
Duplicate of #1305, though useful to know more ways it happens, thanks for reporting it.

**Closed by altrisi** 2022-12-26 14:20 UTC
