### ISSUE TITLE
Carpet will not launch in conjunction with OptiFabric

### ISSUE THREAD

**Issue by Duk-y** [gnembon/fabric-carpet#1766] opened 2023-07-20 21:08 UTC
Replay Mod seems to have the same issue; however no other mods that I have found share it.,

**Comment by silnarm** [comment] 2023-07-22 01:33
https://github.com/Chocohead/OptiFabric/issues/1104

**Comment by altrisi** [comment] 2023-07-22 20:29
Duplicate of some other issue here, I think that optifabric issue has a working optifabric.

**Closed by altrisi** 2023-07-22 20:29 UTC
