### ISSUE TITLE
Issues with /carpet command

### ISSUE THREAD

**Issue by antisoma** [gnembon/fabric-carpet#305] opened 2020-06-01 09:12 UTC
With the most recent snapshot (20w22a) and most recent carpet (1.3.25) the /carpet command becomes inaccessible or has limited options.  Other carpet commands are unaffected (/log, /spawn, /script, etc.).

This happens after using /reload on the server - regardless of whether any datapacks are present or not (have tested with no datapacks - besides vanilla and fabric api).

Unfortunately /reload is required because 20w22a is having issues loading datapacks on server start.

Above, on "limited options" sometimes /carpet is still available but only allows list, removeDefault, and setDefault.

This is on a multiplayer server, with only Fabric and Carpet.  I do run some datapacks but the issue persists with them removed.

**Comment by James103** [comment] 2020-06-01 09:15
Are you still able to edit the locked options from within the config file? What happens if you try to run `/carpet list`?

**Comment by Ghoulboy78** [comment] 2020-06-01 09:32
have you tested without fabric api?

**Comment by Ghoulboy78** [comment] 2020-06-01 09:33
Cannot reproduce in fc 1.3.25, mc 1.15.2

**Comment by antisoma** [comment] 2020-06-01 09:46
When I run /carpet list it does not work or return anything.
I have now tested without fabric api and the issue persists.

**Comment by Ghoulboy78** [comment] 2020-06-01 09:47
yeah, but the other commands still work. and carpet list also works

**Comment by Ghoulboy78** [comment] 2020-06-01 09:47
is your fabric installed correctly with the most recent version?

**Comment by Ghoulboy78** [comment] 2020-06-01 09:48
wait im stupid. I thought it was just 1.3.25. This bug must have to do with the 20w22a, then

**Comment by gnembon** [comment] 2020-06-02 23:01
can replicate. The must have mesup big times with command registration

**Comment by gnembon** [comment] 2020-06-02 23:13
ok, in 22a - reloading re-registeres commands. Not sure why, but it does. Its kinda bad because it means all scarpet registered commands are also gone and maybe I should consider reloading them as well.

**Comment by gnembon** [comment] 2020-06-03 00:09
fixed by https://github.com/gnembon/fabric-carpet/commit/d6845487ce8f6cc56ecfd880916030e97285d3fe
not sure why they've done it this way and not sure why they are not resending the new command tree to clients.

**Closed by gnembon** 2020-06-03 00:09 UTC
