### ISSUE TITLE
24w09a DEV Environment crash Report

### ISSUE THREAD

**Issue by sakura-ryoko** [gnembon/fabric-carpet#1877] opened 2024-03-05 06:33 UTC
Hello,
I was basically doing a basic Integrated / OpenToLan test with MaLiLib and CarpetMod only under IntelliJ IDEA.

At first I thought it was related to something I was doing with MaLiLib under my Snapshot DEV branch, but the crash was not related to what I was doing, testing some network code Mixin Streamlining changes.  It was a CarpetMod crash.

[crash-2024-03-05_01.25.07-client.txt](https://github.com/gnembon/fabric-carpet/files/14491352/crash-2024-03-05_01.25.07-client.txt)

CarpetMod is a common part of my Network Testing to verify the Hello Packet handler is working.

To me, the Crash appears to be related to the mod getting confused that it was an Integrated / OpenToLan Server instead of a dedicated Server, as the Mod works fine if I connect to a dedicated server running Carpet Mod.

**Comment by altrisi** [comment] 2024-04-28 20:29
Can you still reproduce this?

What triggered the crash? Tried leaving from a LAN world and it's not triggering for me (in Carpet's env). May have been fixed since. Or does it happens with Carpet in a _different_ dev env? (if so, `run/mods` or maven, and what mappings?)

**Comment by sakura-ryoko** [comment] 2024-04-29 04:04
This was a while ago, and only happened once, and I can't reproduce it thus far.  I just wanted to report it, as something to keep an eye out for if the culprit is found down the road.

**Comment by altrisi** [comment] 2024-05-02 18:22
Seems to still be a thing, #1908.

**Comment by altrisi** [comment] 2024-05-05 12:18
Going to close this as a duplicate of #1908 to not have two issues for the same.

**Closed by altrisi** 2024-05-05 12:18 UTC
