### ISSUE TITLE
Lagging particle effects when loaded with optifine

### ISSUE THREAD

**Issue by SanchitVartak** [gnembon/fabric-carpet#444] opened 2020-08-31 08:41 UTC
When loading carpet alongside optifine, various particle effects like block braking, eating, nether portal particles etc are really laggy. Also the animation to pick up items (items getting pulled to player) is laggy. The game itself runs smoothly, no FPS drops. When either Optifine or carpet are loaded on their own, or with other mods, everything works fine. Issue only arises when the two are loaded together.

**Comment by altrisi** [comment] 2020-09-01 20:03
Related or duplicate of #393

**Closed** 2020-09-03 23:53 UTC
